# Generated by Django 5.2.10 on 2026-01-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_session_key_alter_order_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
