# Generated by Django 5.2.10 on 2026-01-20 08:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Комментарий администратора'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(max_length=254, verbose_name='Email клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_first_name',
            field=models.CharField(max_length=50, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_notes',
            field=models.TextField(blank=True, verbose_name='Комментарий клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=20, verbose_name='Телефон клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Доставлен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Дни доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Оплачен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Банковская карта'), ('electronic', 'Электронные деньги'), ('cash', 'Наличные при получении')], default='card', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Ошибка оплаты'), ('refunded', 'Возвращен')], default='pending', max_length=20, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Ключ сессии'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отправлен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.JSONField(verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('confirmed', 'Подтвержден'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен'), ('refunded', 'Возвращен')], default='pending', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма налогов'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='order',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID платежа YooKassa'),
        ),
    ]
