# Generated by Django 5.2.10 on 2026-01-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options_alter_order_admin_notes_and_more'),
    ]

    operations = [
    ]
